version: 2
enable-beta-ecosystems: true
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    versioning-strategy: "increase-if-necessary"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    versioning-strategy: "increase-if-necessary"
    directory: "/importer/"
    schedule:
      interval: "daily"
