include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - packages/*/build/**
    - packages/*/lib/**.g.dart
    - packages/flutter_scene_importer/lib/generated/**
    - packages/flutter_scene_importer/lib/third_party/**
  errors:
    asset_does_not_exist: ignore
    asset_directory_does_not_exist: ignore
    invalid_dependency: ignore
