include: package:flutter_lints/flutter.yaml

analyzer:
  exclude: [
    build/**,
    lib/**.g.dart,
    importer/build/**,
    importer/lib/generated/**,
    examples/**,
  ]
  errors:
    asset_does_not_exist: ignore
    invalid_dependency: ignore
