/// Generates standalone codec libraries and the project registrar from
/// extracted components. The output depends only on the public
/// `package:flutter_scene/fscene.dart` surface plus the user's own source
/// file, so generated files compile in any consuming Flutter project.
library;

import 'package:dart_style/dart_style.dart';
import 'package:scene/scene.dart';
import 'package:scene/schema.dart';

import 'package:flutter_scene_codegen/src/extractor.dart';

const String _header =
    '// GENERATED by flutter_scene_codegen. Do not edit by hand; edit the\n'
    '// annotated component and rerun `dart run flutter_scene_codegen:generate`.\n';

String _format(String source) => DartFormatter(
  languageVersion: DartFormatter.latestLanguageVersion,
).format(source);

/// The codec class name generated for [className].
String codecClassNameFor(String className) => '${className}Codec';

/// Generates the `<basename>.fscene.dart` library for one source file's
/// [components]. [sourceImport] is the import of the user's file, usually
/// its basename since the generated library sits beside it.
String generateCodecLibrary({
  required List<ExtractedComponent> components,
  required String sourceImport,
}) {
  final body = StringBuffer();
  var needsVectorMath = false;
  var needsUiColor = false;
  for (final component in components) {
    final emitter = _CodecEmitter(component);
    body.write(emitter.emit());
    needsVectorMath = needsVectorMath || emitter.needsVectorMath;
    needsUiColor = needsUiColor || emitter.needsUiColor;
  }
  final out = StringBuffer()
    ..writeln(_header)
    ..writeln('library;')
    ..writeln();
  if (needsUiColor) out.writeln("import 'dart:ui' show Color;");
  out.writeln("import 'package:flutter_scene/fscene.dart';");
  if (needsVectorMath) {
    out.writeln("import 'package:vector_math/vector_math.dart';");
  }
  out
    ..writeln("import '${_escape(sourceImport)}';")
    ..write(body);
  return _format(out.toString());
}

/// Generates the project registrar library. Each codec library entry pairs
/// its import URI with the codec class names it declares; each dependency
/// registrar pairs an import URI with a registrar function taking an
/// optional registry positionally.
String generateProjectRegistrar({
  required List<({String importUri, List<String> codecClassNames})>
  codecLibraries,
  List<({String importUri, String functionName})> dependencyRegistrars =
      const [],
}) {
  final out = StringBuffer()
    ..writeln(_header)
    ..writeln('library;')
    ..writeln()
    ..writeln("import 'package:flutter_scene/fscene.dart';")
    ..writeln();
  for (var i = 0; i < codecLibraries.length; i++) {
    out.writeln(
      "import '${_escape(codecLibraries[i].importUri)}' as codecs$i;",
    );
  }
  for (var i = 0; i < dependencyRegistrars.length; i++) {
    out.writeln(
      "import '${_escape(dependencyRegistrars[i].importUri)}' as deps$i;",
    );
  }
  out
    ..writeln()
    ..writeln("/// Registers this project's generated component codecs (and")
    ..writeln('/// dependency package components) into [registry], the')
    ..writeln('/// process default when omitted.')
    ..writeln(
      'void registerProjectComponents([FsceneComponentRegistry? registry]) {',
    )
    ..writeln('  final target = registry ?? defaultComponentRegistry();');
  for (var i = 0; i < codecLibraries.length; i++) {
    for (final className in codecLibraries[i].codecClassNames) {
      out.writeln('  target.register(codecs$i.$className());');
    }
  }
  for (var i = 0; i < dependencyRegistrars.length; i++) {
    out.writeln('  deps$i.${dependencyRegistrars[i].functionName}(target);');
  }
  if (codecLibraries.isEmpty && dependencyRegistrars.isEmpty) {
    out.writeln('  // No components declared yet.');
  }
  out.writeln('}');
  return _format(out.toString());
}

class _CodecEmitter {
  _CodecEmitter(this.component);

  final ExtractedComponent component;
  bool needsVectorMath = false;
  bool needsUiColor = false;

  String emit() {
    final out = StringBuffer();
    final className = component.className;
    final codecName = codecClassNameFor(className);
    final schema = component.schema;
    out
      ..writeln()
      ..writeln('/// Generated codec for [$className].')
      ..writeln(
        'class $codecName extends DeclarativeComponentCodec<$className> {',
      )
      ..writeln('  @override')
      ..writeln('  String get type => ${_str(schema.type)};')
      ..writeln();
    if (schema.doc != null ||
        schema.icon != null ||
        schema.formerTypes.isNotEmpty ||
        schema.gizmo != null) {
      out
        ..writeln('  @override')
        ..writeln('  ComponentSchema get schema => ComponentSchema(')
        ..writeln('    ${_str(schema.type)},');
      if (schema.doc != null) out.writeln('    doc: ${_str(schema.doc!)},');
      if (schema.icon != null) out.writeln('    icon: ${_str(schema.icon!)},');
      if (schema.category != null) {
        out.writeln('    category: ${_str(schema.category!)},');
      }
      if (schema.formerTypes.isNotEmpty) {
        out.writeln('    formerTypes: ${_strList(schema.formerTypes)},');
      }
      out.writeln('    properties: propertySchema,');
      if (schema.gizmo != null) {
        // Emitted through the JSON form so the generated code stays a plain
        // literal regardless of which primitives the spec uses.
        out.writeln(
          '    gizmo: GizmoSpec.fromJson(const '
          '${_jsonLiteral(schema.gizmo!.toJson())}),',
        );
      }
      out
        ..writeln('  );')
        ..writeln();
    }
    out
      ..writeln('  @override')
      ..writeln('  List<ComponentField<$className>> get fields => [');
    for (final property in component.properties) {
      out.write(_field(property));
    }
    out
      ..writeln('  ];')
      ..writeln()
      ..writeln('  @override')
      ..writeln('  $className create(PropertyReader props) => $className();')
      ..writeln('}');
    return out.toString();
  }

  String _field(ExtractedProperty property) {
    final def = property.def;
    switch (def.kind) {
      case ComponentPropertyKind.boolean:
        if (!property.nullable &&
            def.defaultValue is BoolValue &&
            def.constraints.isEmpty) {
          return _factoryField(
            property,
            'boolean',
            'defaultValue: ${(def.defaultValue! as BoolValue).value},',
            withConstraints: false,
          );
        }
        return _rawField(
          property,
          read: (target) => 'BoolValue($target)',
          write: (name) => 'if (v is BoolValue) c.$name = v.value;',
        );
      case ComponentPropertyKind.integer:
        if (!property.nullable && def.defaultValue is IntValue) {
          return _factoryField(
            property,
            'integer',
            'defaultValue: ${(def.defaultValue! as IntValue).value},',
          );
        }
        return _rawField(
          property,
          read: (target) => 'IntValue($target)',
          write: (name) => 'if (v is IntValue) c.$name = v.value;',
        );
      case ComponentPropertyKind.number:
        if (!property.nullable && def.defaultValue is DoubleValue) {
          return _factoryField(
            property,
            'number',
            'defaultValue: '
                '${_num((def.defaultValue! as DoubleValue).value)},',
          );
        }
        return _rawField(
          property,
          read: (target) => 'DoubleValue($target)',
          writeBlock: (name) => '''
        final number = switch (v) {
          DoubleValue(:final value) => value,
          IntValue(:final value) => value.toDouble(),
          _ => null,
        };
        if (number != null) c.$name = number;''',
        );
      case ComponentPropertyKind.string:
        if (property.enumTypeName != null) return _enumField(property);
        if (!property.nullable && def.defaultValue is StringValue) {
          return _factoryField(
            property,
            'string',
            'defaultValue: ${_str((def.defaultValue! as StringValue).value)},',
          );
        }
        return _rawField(
          property,
          read: (target) => 'StringValue($target)',
          write: (name) => 'if (v is StringValue) c.$name = v.value;',
        );
      case ComponentPropertyKind.assetRef:
        return _rawField(
          property,
          read: (target) => 'StringValue($target)',
          write: (name) => 'if (v is StringValue) c.$name = v.value;',
        );
      case ComponentPropertyKind.vec2:
        return _vectorField(property, 'vec2', 'Vec2Value');
      case ComponentPropertyKind.vec3:
        return _vectorField(property, 'vec3', 'Vec3Value');
      case ComponentPropertyKind.vec4:
        return _vectorField(property, 'vec4', 'Vec4Value');
      case ComponentPropertyKind.quaternion:
        return _rawField(
          property,
          read: (target) => 'QuaternionValue($target.clone())',
          write: (name) =>
              'if (v is QuaternionValue) c.$name = v.value.clone();',
        );
      case ComponentPropertyKind.matrix4:
        return _rawField(
          property,
          read: (target) => 'Matrix4Value($target.clone())',
          write: (name) => 'if (v is Matrix4Value) c.$name = v.value.clone();',
        );
      case ComponentPropertyKind.color:
        needsUiColor = true;
        return _rawField(
          property,
          read: (target) =>
              'ColorValue($target.r, $target.g, $target.b, $target.a)',
          writeBlock: (name) =>
              '''
        if (v is ColorValue) {
          c.$name = Color.from(alpha: v.a, red: v.r, green: v.g, blue: v.b);
        }''',
        );
      case ComponentPropertyKind.resourceRef:
        return _resourceField(property);
      case ComponentPropertyKind.nodeRef:
        return _nodeField(property);
      default:
        // TODO(compound-kinds): list/map/object/union/distribution/curve/
        // gradient properties need hand-written codecs for now.
        return '    // ${def.name}: unsupported kind ${def.kind.name}, '
            'field omitted.\n';
    }
  }

  String _factoryField(
    ExtractedProperty property,
    String factory,
    String defaultLine, {
    bool withConstraints = true,
  }) {
    final def = property.def;
    final name = def.name;
    return '''
    ComponentField.$factory(
      ${_str(name)},
      $defaultLine
${_commonFactoryLines(def, withConstraints: withConstraints)}      get: (c) => c.$name,
      set: (c, v) => c.$name = v,
    ),
''';
  }

  String _commonFactoryLines(
    ComponentPropertyDef def, {
    bool withConstraints = true,
  }) {
    final out = StringBuffer();
    if (def.doc != null) out.writeln('      doc: ${_str(def.doc!)},');
    if (def.group != null) out.writeln('      group: ${_str(def.group!)},');
    if (withConstraints && def.constraints.isNotEmpty) {
      out.writeln(
        '      constraints: ${_constraints(def.constraints, constContext: false)},',
      );
    }
    if (def.formerNames.isNotEmpty) {
      out.writeln('      formerNames: ${_strList(def.formerNames)},');
    }
    if (def.transient) out.writeln('      transient: true,');
    return out.toString();
  }

  String _enumField(ExtractedProperty property) {
    final def = property.def;
    final name = def.name;
    final enumType = property.enumTypeName!;
    final defaultValue = def.defaultValue;
    if (property.enumResolved &&
        !property.nullable &&
        defaultValue is StringValue &&
        def.constraints.isEmpty) {
      return '''
    ComponentField.enumString(
      ${_str(name)},
      values: $enumType.values,
      defaultValue: $enumType.${defaultValue.value},
${_commonFactoryLines(def, withConstraints: false)}      get: (c) => c.$name,
      set: (c, v) => c.$name = v,
    ),
''';
    }
    // Reading `.name` needs no import of the enum type; writing does.
    final write = property.enumResolved
        ? '''
      write: (c, v, _) {
        if (v is! StringValue) return;
        final match = $enumType.values.asNameMap()[v.value];
        if (match != null) c.$name = match;
      },
'''
        : '      // TODO(tier2-resolution): $enumType is declared in another\n'
              '      // file, so the write binding cannot name it; property is\n'
              '      // read-only until cross-file resolution lands.\n';
    final read = property.nullable
        ? '''
      read: (c, _) {
        final value = c.$name;
        return value == null ? null : StringValue(value.name);
      },
'''
        : '      read: (c, _) => StringValue(c.$name.name),\n';
    return '''
    ComponentField(
      ${_def(def)},
$read$write    ),
''';
  }

  String _vectorField(
    ExtractedProperty property,
    String factory,
    String valueClass,
  ) {
    final def = property.def;
    final name = def.name;
    final vectorDefault = switch (def.defaultValue) {
      Vec2Value(:final value) => _vectorCtor('Vector2', value.storage),
      Vec3Value(:final value) => _vectorCtor('Vector3', value.storage),
      Vec4Value(:final value) => _vectorCtor('Vector4', value.storage),
      _ => null,
    };
    // The vec4 factory carries no constraints parameter.
    final withConstraints = factory != 'vec4';
    if (!property.nullable &&
        vectorDefault != null &&
        (withConstraints || def.constraints.isEmpty)) {
      return '''
    ComponentField.$factory(
      ${_str(name)},
      defaultValue: () => $vectorDefault,
${_commonFactoryLines(def, withConstraints: withConstraints)}      get: (c) => c.$name,
      set: (c, v) => c.$name = v,
    ),
''';
    }
    final write = property.normalized
        ? '''
      write: (c, v, _) {
        if (v is! $valueClass) return;
        final vector = v.value.clone();
        if (vector.length2 > 0) vector.normalize();
        c.$name = vector;
      },
'''
        : '''
      write: (c, v, _) {
        if (v is $valueClass) c.$name = v.value.clone();
      },
''';
    final read = property.nullable
        ? '''
      read: (c, _) {
        final value = c.$name;
        return value == null ? null : $valueClass(value.clone());
      },
'''
        : '      read: (c, _) => $valueClass(c.$name.clone()),\n';
    return '''
    ComponentField(
      ${_def(def)},
$read$write    ),
''';
  }

  String _resourceField(ExtractedProperty property) {
    final def = property.def;
    final name = def.name;
    final resourceKind = def.resourceKind ?? '';
    final realizeCall = switch (resourceKind) {
      'geometry' => 'resources.geometry(id)',
      'material' => 'resources.material(id)',
      'texture' => 'resources.texture(id)',
      _ => null,
    };
    final set = realizeCall == null
        // TODO(resource-kind): only geometry/material/texture resources have
        // a public realizer entry point; other kinds get no write binding.
        ? ''
        : '''
      set: (c, id, context) {
        final resources = context.resources;
        if (resources == null) return;
        c.$name = $realizeCall;
      },
''';
    return '''
    ComponentField.resourceRef(
      ${_str(name)},
      resourceKind: ${_str(resourceKind)},
${_commonFactoryLines(def, withConstraints: false)}      get: (c, context) => resourceRefOf(c.$name, context)?.id,
$set    ),
''';
  }

  String _nodeField(ExtractedProperty property) {
    final def = property.def;
    final name = def.name;
    return '''
    ComponentField(
      ${_def(def)},
      read: (c, _) => nodeRefOf(c.$name),
      write: (c, v, context) {
        if (v is! NodeRefValue) return;
        context.afterRealize.add(() {
          final node = context.resolveNode?.call(v.id);
          if (node != null) c.$name = node;
        });
      },
    ),
''';
  }

  /// A raw field: [read] builds the value expression from a target
  /// expression (`c.name` or a null-checked local), [write]/[writeBlock]
  /// apply an incoming `v` to the component `c`.
  String _rawField(
    ExtractedProperty property, {
    required String Function(String target) read,
    String Function(String name)? write,
    String Function(String name)? writeBlock,
  }) {
    final def = property.def;
    final name = def.name;
    final readSource = property.nullable
        ? '''
      read: (c, _) {
        final value = c.$name;
        return value == null ? null : ${read('value')};
      },
'''
        : '      read: (c, _) => ${read('c.$name')},\n';
    final writeSource = writeBlock != null
        ? '      write: (c, v, _) {\n${writeBlock(name)}\n      },\n'
        : '      write: (c, v, _) {\n        ${write!(name)}\n      },\n';
    return '''
    ComponentField(
      ${_def(def)},
$readSource$writeSource    ),
''';
  }

  String _def(ComponentPropertyDef def) {
    final defaultValue = def.defaultValue;
    final isConst =
        defaultValue == null ||
        defaultValue is BoolValue ||
        defaultValue is IntValue ||
        defaultValue is DoubleValue ||
        defaultValue is StringValue ||
        defaultValue is ColorValue;
    final parts = <String>[
      _str(def.name),
      'ComponentPropertyKind.${def.kind.name}',
    ];
    if (defaultValue != null) {
      parts.add('defaultValue: ${_value(defaultValue, constContext: isConst)}');
    }
    if (def.doc != null) parts.add('doc: ${_str(def.doc!)}');
    if (def.group != null) parts.add('group: ${_str(def.group!)}');
    if (def.resourceKind != null) {
      parts.add('resourceKind: ${_str(def.resourceKind!)}');
    }
    if (def.options != null) parts.add('options: ${_strList(def.options!)}');
    if (def.constraints.isNotEmpty) {
      parts.add(
        'constraints: ${_constraints(def.constraints, constContext: isConst)}',
      );
    }
    if (def.formerNames.isNotEmpty) {
      parts.add('formerNames: ${_strList(def.formerNames)}');
    }
    if (def.transient) parts.add('transient: true');
    final prefix = isConst ? 'const ' : '';
    return '${prefix}ComponentPropertyDef(\n'
        '        ${parts.join(',\n        ')},\n'
        '      )';
  }

  String _value(PropertyValue value, {required bool constContext}) {
    final prefix = constContext ? '' : 'const ';
    switch (value) {
      case BoolValue(:final value):
        return '${prefix}BoolValue($value)';
      case IntValue(:final value):
        return '${prefix}IntValue($value)';
      case DoubleValue(:final value):
        return '${prefix}DoubleValue(${_num(value)})';
      case StringValue(:final value):
        return '${prefix}StringValue(${_str(value)})';
      case ColorValue(:final r, :final g, :final b, :final a):
        return '${prefix}ColorValue('
            '${_num(r)}, ${_num(g)}, ${_num(b)}, ${_num(a)})';
      case Vec2Value(:final value):
        return 'Vec2Value(${_vectorCtor('Vector2', value.storage)})';
      case Vec3Value(:final value):
        return 'Vec3Value(${_vectorCtor('Vector3', value.storage)})';
      case Vec4Value(:final value):
        return 'Vec4Value(${_vectorCtor('Vector4', value.storage)})';
      case QuaternionValue(:final value):
        needsVectorMath = true;
        return 'QuaternionValue(Quaternion(${_num(value.x)}, '
            '${_num(value.y)}, ${_num(value.z)}, ${_num(value.w)}))';
      default:
        throw UnsupportedError(
          'No source form for default ${value.runtimeType}',
        );
    }
  }

  String _vectorCtor(String typeName, List<double> storage) {
    needsVectorMath = true;
    return '$typeName(${storage.map(_num).join(', ')})';
  }

  String _constraints(
    List<PropertyConstraint<Object?>> constraints, {
    required bool constContext,
  }) {
    final prefix = constContext ? '' : 'const ';
    final parts = [
      for (final constraint in constraints) _constraint(constraint),
    ];
    return '$prefix[${parts.join(', ')}]';
  }

  String _constraint(PropertyConstraint<Object?> constraint) {
    switch (constraint) {
      case Range(:final min, :final max):
        return 'Range(${_numOrNull(min)}, ${_numOrNull(max)})';
      case SoftRange(:final min, :final max):
        return 'SoftRange(${_num(min)}, ${_num(max)})';
      case IntRange(:final min, :final max):
        return 'IntRange(${min ?? 'null'}, ${max ?? 'null'})';
      case Step(:final step):
        return 'Step(${_num(step)})';
      case PowerOfTwo(:final min, :final max):
        return 'PowerOfTwo(min: $min${max == null ? '' : ', max: $max'})';
      case AngleRadians():
        return 'AngleRadians()';
      case RgbColor():
        return 'RgbColor()';
      case Normalized():
        return 'Normalized()';
      case LayerMask32():
        return 'LayerMask32()';
      case Multiline():
        return 'Multiline()';
      case TextPattern(:final pattern):
        return 'TextPattern(${_str(pattern)})';
      case AssetExtensions(:final extensions):
        return 'AssetExtensions(${_strList(extensions)})';
      case MinCount(:final count):
        return 'MinCount($count)';
      case SortedDescending(:final fieldName):
        return 'SortedDescending(${_str(fieldName)})';
      default:
        throw UnsupportedError(
          'No source form for constraint ${constraint.runtimeType}',
        );
    }
  }
}

String _numOrNull(double? value) => value == null ? 'null' : _num(value);

String _num(double value) {
  if (value == value.roundToDouble() && value.abs() < 1e15) {
    return '${value.toInt()}.0';
  }
  return '$value';
}

String _escape(String value) => value
    .replaceAll('\\', '\\\\')
    .replaceAll("'", "\\'")
    .replaceAll('\$', '\\\$')
    .replaceAll('\n', '\\n');

String _str(String value) => "'${_escape(value)}'";

String _strList(List<String> values) => '[${values.map(_str).join(', ')}]';

/// A JSON-shaped value (maps, lists, strings, numbers, bools) as a Dart
/// const-literal source string.
String _jsonLiteral(Object? value) => switch (value) {
  null => 'null',
  final String text => _str(text),
  final bool flag => '$flag',
  final num number => '$number',
  final List<Object?> list => '[${list.map(_jsonLiteral).join(', ')}]',
  final Map<Object?, Object?> map =>
    '{${map.entries.map((entry) => '${_str(entry.key! as String)}: '
        '${_jsonLiteral(entry.value)}').join(', ')}}',
  _ => 'null',
};
