// Regenerates lib/src/texture/basisu/etc1s_bc1_table_data.dart, so apps skip
// the half-second search at load time.
//
//   dart run tool/generate_etc1s_tables.dart

import 'dart:convert';
import 'dart:io';

import 'package:flutter_scene/src/texture/basisu/etc1s_tables.dart';

const String _outputPath = 'lib/src/texture/basisu/etc1s_bc1_table_data.dart';

void main() {
  final watch = Stopwatch()..start();
  final buffer = StringBuffer()
    ..writeln('// Generated by tool/generate_etc1s_tables.dart. Do not edit.')
    ..writeln('//')
    ..writeln('// The ETC1S-to-BC1 endpoint tables (see buildEtc1sBc1Table in')
    ..writeln('// etc1s_tables.dart): a (low, high) byte pair per solution,')
    ..writeln('// base64 encoded.')
    ..writeln();
  for (final bits in [5, 6]) {
    final encoded = base64.encode(buildEtc1sBc1Table(bits));
    buffer
      ..writeln('/// The $bits-bit ETC1S-to-BC1 table.')
      ..writeln('const String etc1sBc1Table${bits}Data =');
    const width = 72;
    for (var i = 0; i < encoded.length; i += width) {
      final end = i + width < encoded.length ? i + width : encoded.length;
      final last = end == encoded.length;
      buffer.writeln("    '${encoded.substring(i, end)}'${last ? ';' : ''}");
    }
    buffer.writeln();
  }
  File(_outputPath).writeAsStringSync('${buffer.toString().trimRight()}\n');
  stdout.writeln('Wrote $_outputPath in ${watch.elapsedMilliseconds} ms.');
}
