name: flutter_scene_importer
description: "An offline 3D model importer for Flutter. Converts glTF files into the Flutter Scene model format."
version: 0.10.0
homepage: https://github.com/bdero/flutter_scene
platforms:
  linux:
  macos:
  windows:
  ios:
  android:

resolution: workspace

environment:
  sdk: ^3.7.0
  flutter: ">=3.29.0-1.0.pre.242"

dependencies:
  args: ^2.5.0
  flutter:
    sdk: flutter
  flutter_gpu:
    sdk: flutter
  hooks: ^1.0.0
  image: ^4.5.0
  logging: ^1.2.0
  vector_math: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
