// Regenerates lib/src/core/key_codes.g.dart from the Flutter SDK's physical
// key data, pairing each USB HID usage with its W3C UI Events `code` name.
//
//   dart run tool/generate_key_codes.dart <flutter>/dev/tools/gen_keycodes/data/physical_key_data.g.json

import 'dart:convert';
import 'dart:io';

void main(List<String> args) {
  if (args.length != 1) {
    stderr.writeln('usage: generate_key_codes.dart <physical_key_data.g.json>');
    exit(64);
  }
  final data = jsonDecode(File(args.single).readAsStringSync()) as Map;
  final entries = <(int, String)>[];
  for (final value in data.values) {
    final usb = (value['scanCodes'] as Map)['usb'];
    final code = (value['names'] as Map)['chromium'];
    if (usb is int && code is String) entries.add((usb, code));
  }
  entries.sort((a, b) => a.$1.compareTo(b.$1));
  final out = StringBuffer()
    ..writeln('// GENERATED by tool/generate_key_codes.dart. Do not edit.')
    ..writeln('// ignore_for_file: type=lint')
    ..writeln()
    ..writeln('/// USB HID usage to W3C UI Events `code` name.')
    ..writeln('const Map<int, String> kKeyCodeNames = <int, String>{');
  for (final (usb, code) in entries) {
    out.writeln("  0x${usb.toRadixString(16).padLeft(8, '0')}: '$code',");
  }
  out.writeln('};');
  File('lib/src/core/key_codes.g.dart').writeAsStringSync(out.toString());
  stdout.writeln('Wrote ${entries.length} key codes.');
}
