name: Flutter CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  lint-and-test:
    name: Lint and Test
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: master
      - run: dart --version
      - run: flutter --version
      - name: Resolve workspace dependencies
        run: flutter pub get
      - name: Enable asset building
        run: flutter config --enable-native-assets
      - name: Lint analysis
        run: dart analyze packages examples
      - name: Dart format
        run: dart format --output none --set-exit-if-changed $(find . -name '**.dart' -not -name '*_flatbuffers.dart' -not -path '*/build/*' -not -path '*/third_party/*')
      - name: Run flutter_scene tests
        working-directory: packages/flutter_scene
        run: flutter test --enable-impeller
      - name: Run flutter_scene_importer tests
        working-directory: packages/flutter_scene_importer
        run: flutter test --enable-impeller
