name: Flutter CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  lint-and-test:
    name: Lint and Test
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: master
      - run: dart --version
      - run: flutter --version
      - run: flutter pub get
      - name: enable asset building
        run: flutter config --enable-native-assets
      - name: Lint analysis
        run: dart analyze
      - name: Dart format
        run: dart format --output none --set-exit-if-changed $(find . -name '**.dart' -not -name '*_flatbuffers.dart' -not -path '*/build/*')
      - name: dart fix
        run: dart fix --dry-run
      - name: Run tests
        run: flutter test --enable-impeller
